export const LAB_CODE_LABELS: Record<string, string> = {
  lab_locked: "Confirme novamente seu e-mail e senha de proprietário para abrir a central.",
  lab_disabled: "A central está desativada. Nenhum teste novo será iniciado.",
  invalid_credentials: "E-mail ou senha inválidos, ou conta sem permissão de proprietário.",
  rate_limited: "Muitas tentativas. Aguarde antes de tentar novamente.",
  github_not_configured: "Falta configurar a credencial restrita do runner do GitHub.",
  github_access_denied: "O GitHub não autorizou iniciar ou consultar a suíte.",
  github_unavailable: "Não foi possível confirmar a resposta do GitHub agora.",
  internal_dispatch_unknown: "O runner pode ter recebido a solicitação. Não repetimos o disparo para evitar duplicidade.",
  internal_passed: "A suíte selecionada passou nessa versão. Isso não comprova um atendimento real.",
  internal_failed: "A suíte encontrou uma falha. Abra os detalhes do runner para investigar.",
  internal_running: "A suíte está em execução no runner separado do GitHub.",
  internal_cancelled: "O runner foi cancelado. Esta execução não conta como aprovada.",
  real_test_dependencies_pending: "Os testes reais aguardam conclusão e validação do isolamento, cobrança e encerramento seguro.",
  sender_has_active_runs: "Pare e encerre as execuções antes de desconectar o WhatsApp testador.",
  sender_creation_unconfirmed: "A criação da conexão não foi confirmada. A reserva foi preservada para evitar outra instância.",
  sender_missing_review_required: "A instância reservada não foi encontrada. É necessária revisão antes de recriar.",
  sender_qr_unavailable: "O provedor ainda não forneceu um QR válido. Tente atualizar a conexão.",
  sender_provider_unavailable: "A Evolution não respondeu à consulta de conexão.",
  sender_number_already_in_use: "Esse número já pertence a uma conexão do sistema ou de cliente. Use outro número dedicado ao laboratório.",
  sender_isolation_unconfirmed: "Não foi possível confirmar que o número é exclusivo do laboratório.",
  lab_webhook_url_missing: "Falta configurar o endereço HTTPS do webhook exclusivo do laboratório.",
  deadline_reached: "O tempo máximo terminou. Nenhuma nova mensagem do testador pode sair.",
  provider_receipt_unknown: "Não foi possível confirmar a entrega. O teste foi interrompido sem reenvio automático.",
  deployment_changed: "O sistema mudou de versão. Execute novamente as verificações na versão atual.",
  preflight_failed: "Uma ou mais verificações obrigatórias não foram aprovadas.",
  destination_not_authorized: "O destino não está na lista autorizada, ou foi revogado. Nenhuma mensagem saiu.",
  destination_unresolved: "Não foi possível resolver com exatidão o número, a conexão e o agente de destino.",
  destination_confirmation_failed: "A confirmação do destino não foi gravada. O teste não começou.",
  same_number_rejected: "O número testador e o número atendido precisam ser diferentes.",
  message_limit: "O limite de mensagens deste perfil foi atingido.",
  budget_exhausted: "O orçamento reservado para esta execução acabou.",
  run_not_active: "Esta execução não está mais aceitando mensagens.",
  step_already_queued: "Essa mensagem já estava na fila. Nada foi enviado em duplicidade.",
  sender_not_connected: "O WhatsApp testador não está conectado.",
  target_jid_invalid: "O número de destino não é um telefone WhatsApp válido.",
  send_transport_unknown: "Não houve resposta do provedor no envio. Interrompido sem reenvio.",
  send_status_unknown: "O provedor respondeu de forma indeterminada. Interrompido sem reenvio.",
  receipt_missing: "O provedor aceitou o envio sem devolver identificador. Resultado inconclusivo.",
  waiting_agent_turn: "Aguardando o turno do agente. A Evolution pode levar cerca de um minuto.",
  waiting_owner_message: "Aguardando sua próxima mensagem no painel.",
  reply_received: "O agente respondeu dentro da janela.",
  no_reply_within_window: "O agente não respondeu dentro da janela de espera.",
  silence_confirmed: "O silêncio esperado foi confirmado.",
  silence_expected_but_agent_replied: "Era esperado silêncio, mas o agente respondeu.",
  awaiting_effect_verification: "A resposta chegou, mas o efeito ainda não foi confirmado no banco.",
  turn_still_open: "O turno ainda está aberto.",
  stopped_by_owner: "Você interrompeu esta execução.",
  stop_all_requested: "Todas as execuções abertas foram interrompidas.",
  owner_inactive: "A conta de proprietário não está ativa.",
};
export function labCodeLabel(code: string): string {
  return LAB_CODE_LABELS[code] ?? `Não foi possível concluir esta etapa. Código para investigação: ${code}`;
}
export const LAB_STATUS_LABELS: Record<string, string> = {
  queued: "Na fila", running: "Executando", paused: "Pausado", waiting_reply: "Aguardando agente",
  waiting_input: "Aguardando ação", stopping: "Encerrando", completed: "Concluído", failed: "Falhou", cancelled: "Cancelado",
};
export const LAB_VERDICT_LABELS: Record<string, string> = {
  passed: "Aprovado", failed: "Falhou", expected_block: "Bloqueio esperado", inconclusive: "Inconclusivo", not_executed: "Não executado",
};
