export const LAB_CODE_LABELS: Record<string, string> = {
  lab_locked: "A Central de Testes está bloqueada. Libere novamente usando sua sessão de proprietário.",
  admin_session_required: "Sua sessão de administrador expirou. Entre novamente no painel para liberar a Central de Testes.",
  lab_disabled: "A central está desativada. Nenhum teste novo será iniciado.",
  invalid_credentials: "E-mail ou senha inválidos, ou conta sem permissão de proprietário.",
  rate_limited: "Muitas tentativas. Aguarde antes de tentar novamente.",
  github_not_configured: "Falta configurar a credencial restrita do runner do GitHub.",
  github_access_denied: "O GitHub não autorizou iniciar ou consultar a suíte.",
  github_unavailable: "Não foi possível confirmar a resposta do GitHub agora.",
  internal_dispatch_unknown: "O runner pode ter recebido a solicitação. Não repetimos o disparo para evitar duplicidade.",
  internal_passed: "A suíte selecionada passou nessa versão. Isso não comprova um atendimento real.",
  internal_failed: "A suíte encontrou uma falha. Abra os detalhes do runner para investigar.",
  internal_running: "A suíte está em execução no runner separado do GitHub.",
  internal_cancelled: "O runner foi cancelado. Esta execução não conta como aprovada.",
  real_test_dependencies_pending: "Os testes reais aguardam conclusão e validação do isolamento, cobrança e encerramento seguro.",
  paid_lab_execution_pending: "IA testadora e avaliação paga aguardam a validação do controle de custos.",
  cleanup_ownership_pending: "A limpeza aguarda comprovação exata de quais recursos pertencem ao teste. Nada foi removido.",
  original_billing_isolation_pending: "O teste no agente original aguarda validação de cobrança e permissões. Use a cópia isolada.",
  receiver_target_mismatch: "O WhatsApp receptor está ligado a outra cópia. Encerre os testes e desconecte-o antes de escolher outro agente.",
  target_configuration_changed: "A configuração mudou durante o teste. A versão anterior não será considerada aprovada.",
  lab_automation_stop_unconfirmed: "A parada das automações ainda não foi confirmada. O teste requer revisão; não foi marcado como concluído.",
  sender_has_active_runs: "Pare e encerre as execuções antes de desconectar o WhatsApp testador.",
  sender_creation_unconfirmed: "A criação da conexão não foi confirmada. A reserva foi preservada para evitar outra instância.",
  sender_missing_review_required: "A instância reservada não foi encontrada. É necessária revisão antes de recriar.",
  sender_qr_unavailable: "O provedor ainda não forneceu um QR válido. Tente atualizar a conexão.",
  sender_provider_unavailable: "A Evolution não respondeu à consulta de conexão.",
  sender_number_already_in_use: "Esse número já pertence a uma conexão do sistema ou de cliente. Use outro número dedicado ao laboratório.",
  sender_isolation_unconfirmed: "Não foi possível confirmar que o número é exclusivo do laboratório.",
  sender_other_provider_connected: "O testador já usa o outro método. Use \"Trocar para\" para desconectá-lo e conectar pelo outro.",
  receiver_other_provider_connected: "A cópia já usa o outro método. Use \"Trocar para\" para desconectá-la e conectar pela outra.",
  sender_switch_unconfirmed: "A desconexão do testador não foi confirmada. Nada novo foi conectado: verifique a conexão e tente de novo.",
  receiver_switch_unconfirmed: "A desconexão da cópia não foi confirmada. Nada novo foi conectado: verifique a conexão e tente de novo.",
  receiver_has_active_runs: "Pare e encerre as execuções antes de trocar ou desconectar o número da cópia.",
  invalid_connection_provider: "Método de conexão inválido. Escolha QR Code (Evolution) ou API Oficial Meta.",
  invalid_source_agent: "Escolha o cliente e o agente antes de conectar a linha da cópia isolada.",
  sender_removal_unconfirmed: "A remoção da conexão do testador não foi confirmada pelo provedor. Nada novo foi conectado.",
  receiver_removal_unconfirmed: "A remoção da conexão da cópia não foi confirmada pelo provedor. Nada novo foi conectado.",
  meta_server_not_configured: "A conexão oficial da Meta não está configurada no servidor.",
  meta_signup_code_invalid: "A Meta não devolveu um código de conexão válido. Tente novamente.",
  meta_waba_invalid: "A conta WhatsApp Business devolvida pela Meta é inválida.",
  meta_phone_id_invalid: "O número devolvido pela Meta é inválido.",
  meta_token_exchange_failed: "A Meta recusou a troca do código de conexão. Tente novamente.",
  meta_long_lived_token_required: "A Meta não confirmou uma credencial durável. A conexão não foi salva.",
  meta_number_verification_failed: "Não foi possível confirmar o número na API Oficial Meta.",
  meta_onboarding_incomplete: "A Meta não confirmou o webhook ou o registro do número. A conexão não foi ativada.",
  meta_outside_24h_window: "A Meta bloqueou a mensagem livre fora da janela de 24 horas. Inicie a conversa com esse número ou use um template aprovado.",
  lab_webhook_url_missing: "Falta configurar o endereço HTTPS do webhook exclusivo do laboratório.",
  deadline_reached: "O tempo máximo terminou. Nenhuma nova mensagem do testador pode sair.",
  provider_receipt_unknown: "Não foi possível confirmar a entrega. O teste foi interrompido sem reenvio automático.",
  deployment_changed: "O sistema mudou de versão. Execute novamente as verificações na versão atual.",
  preflight_failed: "Uma ou mais verificações obrigatórias não foram aprovadas.",
  destination_not_authorized: "O destino não está na lista autorizada, ou foi revogado. Nenhuma mensagem saiu.",
  destination_unresolved: "Não foi possível resolver com exatidão o número, a conexão e o agente de destino.",
  destination_confirmation_failed: "A confirmação do destino não foi gravada. O teste não começou.",
  same_number_rejected: "O número testador e o número atendido precisam ser diferentes.",
  message_limit: "O limite de mensagens deste perfil foi atingido.",
  budget_exhausted: "O orçamento reservado para esta execução acabou.",
  run_not_active: "Esta execução não está mais aceitando mensagens.",
  step_already_queued: "Essa mensagem já estava na fila. Nada foi enviado em duplicidade.",
  sender_not_connected: "O WhatsApp testador não está conectado.",
  target_jid_invalid: "O número de destino não é um telefone WhatsApp válido.",
  send_transport_unknown: "Não houve resposta do provedor no envio. Interrompido sem reenvio.",
  send_status_unknown: "O provedor respondeu de forma indeterminada. Interrompido sem reenvio.",
  receipt_missing: "O provedor aceitou o envio sem devolver identificador. Resultado inconclusivo.",
  waiting_agent_turn: "Aguardando o turno do agente. A Evolution pode levar cerca de um minuto.",
  waiting_owner_message: "Aguardando sua próxima mensagem no painel.",
  reply_received: "O agente respondeu dentro da janela.",
  no_reply_within_window: "O agente não respondeu dentro da janela de espera.",
  silence_confirmed: "O silêncio esperado foi confirmado.",
  silence_expected_but_agent_replied: "Era esperado silêncio, mas o agente respondeu.",
  awaiting_effect_verification: "A resposta chegou, mas o efeito ainda não foi confirmado no banco.",
  turn_still_open: "O turno ainda está aberto.",
  stopped_by_owner: "Você interrompeu esta execução.",
  stop_all_requested: "Todas as execuções abertas foram interrompidas.",
  owner_inactive: "A conta de proprietário não está ativa.",
};
export function labCodeLabel(code: string): string {
  return LAB_CODE_LABELS[code] ?? `Não foi possível concluir esta etapa. Código para investigação: ${code}`;
}
export const LAB_STATUS_LABELS: Record<string, string> = {
  queued: "Na fila", running: "Executando", paused: "Pausado", waiting_reply: "Aguardando agente",
  waiting_input: "Aguardando ação", stopping: "Encerrando", completed: "Concluído", failed: "Falhou", cancelled: "Cancelado",
};
export const LAB_VERDICT_LABELS: Record<string, string> = {
  passed: "Aprovado", failed: "Falhou", expected_block: "Bloqueio esperado", inconclusive: "Inconclusivo", not_executed: "Não executado",
};
