export const COMMON_TIMEZONES: { label: string; value: string }[] = [
  { label: "América/São Paulo (BRT, UTC-3) (padrão)", value: "America/Sao_Paulo" },
  { label: "UTC", value: "UTC" },
  { label: "América/Manaus (AMT, UTC-4)", value: "America/Manaus" },
  { label: "América/Belém (BRT, UTC-3)", value: "America/Belem" },
  { label: "América/Fortaleza (BRT, UTC-3)", value: "America/Fortaleza" },
  { label: "América/Recife (BRT, UTC-3)", value: "America/Recife" },
  { label: "América/New York (EST/EDT)", value: "America/New_York" },
  { label: "América/Chicago (CST/CDT)", value: "America/Chicago" },
  { label: "América/Denver (MST/MDT)", value: "America/Denver" },
  { label: "América/Los Angeles (PST/PDT)", value: "America/Los_Angeles" },
  { label: "América/Mexico City (CST, UTC-6)", value: "America/Mexico_City" },
  { label: "América/Bogotá (COT, UTC-5)", value: "America/Bogota" },
  { label: "América/Lima (PET, UTC-5)", value: "America/Lima" },
  { label: "América/Buenos Aires (ART, UTC-3)", value: "America/Argentina/Buenos_Aires" },
  { label: "América/Santiago (CLT/CLST)", value: "America/Santiago" },
  { label: "Europa/Lisboa (WET/WEST)", value: "Europe/Lisbon" },
  { label: "Europa/Londres (GMT/BST)", value: "Europe/London" },
  { label: "Europa/Madrid (CET/CEST)", value: "Europe/Madrid" },
  { label: "Europa/Paris (CET/CEST)", value: "Europe/Paris" },
  { label: "Ásia/Dubai (GST, UTC+4)", value: "Asia/Dubai" },
  { label: "Ásia/Tóquio (JST, UTC+9)", value: "Asia/Tokyo" },
  { label: "Austrália/Sydney (AEST/AEDT)", value: "Australia/Sydney" },
  { label: "África/Luanda (WAT, UTC+1)", value: "Africa/Luanda" },
];
